version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: fx-pipeline-postgres-1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fxdb
    ports:
      - "5432:5432"
    volumes:
      - ./sql/postgres_init.sql:/docker-entrypoint-initdb.d/init.sql

  clickhouse:
    image: clickhouse/clickhouse-server:23
    container_name: fx-pipeline-clickhouse-1
    restart: always
    environment:
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_DB: fxdb
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ./sql/clickhouse_init.sql:/docker-entrypoint-initdb.d/init.sql

  scheduler:
    build: .
    container_name: fx-pipeline-scheduler
    depends_on:
      - postgres
      - clickhouse
    restart: always